### PR TITLE
Moved get-tested setup to own workflow

### PR DESCRIPTION
**Pull request by mmhat**
This way it can be reused if one does need it in other places and not only for build matrix generation.

### CODE REVIEW

**Comment by Kleidukos** [comment]
@mmhat Is there a concrete use-case for this? I have to admit I can't think of one and thus it's a bit hard to justify keeping it around if nobody uses it.

**Comment by mmhat** [comment]
@Kleidukos  Consider a mono-repo like <https://github.com/dhall-lang/dhall-haskell>:
There, we have the dhall library in one Cabal package and some other packages like dhall-json, dhall-toml, ... that depend on the dhall library. Each of the packages might have different `tested-with` stanzas, and ideally we want the workflow matrix take the versions of all packages into account. Let's assume the following (version numbers are made up):

- The dhall package has `GHC ==9.6.6, GHC ==9.8.2, GHC ==9.10.1` in its `tested-with` stanza
- The dhall-json package has `GHC ==9.8.2, GHC ==9.10.1` in its `tested-with` stanza.
- The dhall-toml package has `GHC ==9.6.6, GHC ==9.8.2` in its `tested-with` stanza.

For the latter two contain only a subset since there might be additional dependencies that don't support some the GHCs listed in the stanza of the dhall library. So, how should the test matrix look like?
Since the mono-repo is acutally quite costly to build we don't want a matrix for each package.
Currently the Dhall project has one matrix build and excludes certain packages in jobs using Shell conditionals.
What I'd like to try is doing something similar using `get-tested` (in fact, that also motivated #49 and #50):

1. Generate a build matrix including the versions of all packages in a project.
2. Fetch the `get-tested` executable in the matrix job (this PR).
3. Then in a step:
   ```
   for package in PACKAGES; do
     if get-tested check "${package}" ${{ matrix.ghc }}; then
       DO_SOMETHING
     fi
   done
   ```

Does that make sense?

**Comment by Kleidukos** [comment]
I see. In servant `get-tested` is used on the `servant.cabal` file, which is the foundation for all other packages in the repository, and thus gives the widest possible support window for other packages: https://github.com/haskell-servant/servant/blob/master/.github/workflows/master.yml#L20

**Comment by Kleidukos** [comment]
@mmhat I'm going to merge it. Can you test in some of your projects by specifying the commit in the `uses:` stanza?

**Comment by mmhat** [comment]
@Kleidukos Yes, I can do that; But I also included a workflow `test-action.yml` that does checks that here: https://github.com/Kleidukos/get-tested/blob/1a77bbcf38be7d4136194760083325cce6751aec/.github/workflows/test-action.yml#L30

**Pull request merged**
